name: 'Checkin'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '58 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    #runs-on: macos-latest
    runs-on: ubuntu-latest

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2

            
        - name: 'Checkin'
          env:
            BASE_URL: ${{ secrets.BASE_URL }}
            USER_ID: ${{ secrets.USER_ID }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 ./main.py
