name: 'A-Checkin'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '58 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2

        - name: Delete old workflow runs
          uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
          with:
            repository: ${{ github.repository }}   # replace this with your own repository such as >> owner/repo
            older-than-seconds: 86400          # remove all workflow runs older than 1 day >> 24*60*60=86400
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
        - name: 'Checkin'
          env:
            BASE_URL: ${{ secrets.BASE_URL }}
            USER_ID: ${{ secrets.USER_ID }}
            PASS_WD: ${{ secrets.PASS_WD }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 ./main.py
